function data = importCAPSENSORfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   SQSHFMDAY8NONOMLOGFILE = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   SQSHFMDAY8NONOMLOGFILE = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   SQSHFMday8noNOMlogfile = importfile('SQS_HFM_day8_noNOM_logfile.dat', 2, 35001);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/10/10 09:47:30

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
data = table(dataArray{1:end-1}, 'VariableNames', {'Timestamp','SampleNo','BL16BMOUMAC99AXIS1RBV','BL16BMOUMAC99AXIS2RBV','FMBWAGOAI00','FMBWAGOAI01','FMBWAGOAI02','FMBWAGOAI00_MON','FMBWAGOAI01_MON','FMBWAGOAI02_MON','FMBWAGOAI00_DIST_MON','FMBWAGOAI01_DIST_MON','FMBWAGOAI02_DIST_MON'});
data = table2array(data);
